services:
  - type: web
    name: spacex-falcon9-dashboard
    env: python
    plan: free
    buildCommand: pip install -r dashboard/requirements.txt && pip install -e . && python -m spacex_capstone.train_and_export dashboard/model_artifact.joblib
    startCommand: gunicorn spacex-dash-app:server --chdir dashboard --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
